---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-ease
    kind: solution
    catalog_id: TBD
    offering_id: TBD
    variations:
      - name: standard
        mark_ready: true
        install_type: fullstack
        scc:
          instance_id: <....>
          region: us-south
